export const ROUTES = {
  WELCOME: '/(auth)/welcome',
  LOGIN: '/(auth)/login',
  REGISTER: '/(auth)/register',
  CUSTOMER_HOME: '/(customer)',
  CUSTOMER_BROWSE: '/(customer)/browse',
  CUSTOMER_BOOKINGS: '/(customer)/bookings',
  CUSTOMER_PROFILE: '/(customer)/profile',
  OWNER_DASHBOARD: '/(owner)',
  OWNER_CALENDAR: '/(owner)/calendar',
  OWNER_BOOKINGS: '/(owner)/bookings',
  OWNER_SETTINGS: '/(owner)/settings',
  BOOKING_SELECT_SERVICE: '/booking/select-service',
  BOOKING_SELECT_SLOT: '/booking/select-slot',
  BOOKING_CONFIRM: '/booking/confirm',
  BOOKING_SUCCESS: '/booking/success',
  BOOKING_DETAIL: (id: string) => `/booking-detail/${id}`,
};
