export const STRINGS = {
  APP_NAME: 'CusOwn',
  TAGLINE: 'Premium Salon & Spa Experiences at Your Fingertips',
  WELCOME_TITLE: 'Welcome to CusOwn',
  WELCOME_SUBTITLE: 'Book top-tier stylists, seamless slots, and bespoke self-care services instantly.',
  CONTINUE_GOOGLE: 'Continue with Google',
  LOGIN_EMAIL: 'Login with Email',
  CREATE_ACCOUNT: 'Create Account',
  ALREADY_HAVE_ACCOUNT: 'Already have an account? Sign In',
  NO_ACCOUNT: "Don't have an account? Sign Up",
  EMAIL_PLACEHOLDER: 'Enter your email address',
  PASSWORD_PLACEHOLDER: 'Enter your secure password',
  NAME_PLACEHOLDER: 'Enter your full name',
  ROLE_LABEL: 'Select Your Profile Type',
  ROLE_CUSTOMER_DESC: 'Book appointments and browse curated premium salons.',
  ROLE_OWNER_DESC: 'Manage your salon workflows, schedule calendar, and team slots.',
  CONFIRM_BOOKING: 'Confirm Booking',
  CANCEL_BOOKING: 'Cancel Appointment',
  VIEW_BOOKINGS: 'View My Bookings',
  BOOKING_SUCCESS: 'Appointment Confirmed Successfully!',
  OWNER_STATS_TITLE: "Today's Pulse",
  TOTAL_BOOKINGS: 'Total Appointments',
  PENDING_REQUESTS: 'Awaiting Action',
  REVENUE_TODAY: 'Gross Revenue',
  CONFIRM_ACTION: 'Confirm',
  REJECT_ACTION: 'Reject',
  MARK_NOSHOW: 'Mark No-Show',
  LOGOUT: 'Sign Out',
  ERRORS: {
    REQUIRED_FIELD: 'This field is required',
    INVALID_EMAIL: 'Please enter a valid email address',
    SHORT_PASSWORD: 'Password must contain at least 6 characters',
    GENERIC: 'Something went wrong. Please try again later.',
  },
};
