const BASE_COLORS = {
  primary: '#000000',
  secondary: '#FFFFFF',
  accent: '#FFFFFF',
  white: '#FFFFFF',
  black: '#000000',
};

export const THEME = {
  light: {
    background: '#FFFFFF',
    card: '#F5F5F5',
    text: '#000000',
    textSecondary: '#666666',
    border: '#E5E5E5',
    primary: BASE_COLORS.primary,
    secondary: BASE_COLORS.secondary,
    accent: BASE_COLORS.accent,
    success: '#000000',
    error: '#000000',
    warning: '#000000',
    info: '#000000',
  },
  dark: {
    background: '#000000',
    card: '#000000',
    text: '#FFFFFF',
    textSecondary: '#A0A0A0',
    border: '#1A1A1A',
    primary: '#FFFFFF',
    secondary: '#FFFFFF',
    accent: '#FFFFFF',
    success: '#FFFFFF',
    error: '#FFFFFF',
    warning: '#FFFFFF',
    info: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  typography: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 22,
    xxl: 28,
  },
};
