export const BASE_COLORS = {
  obsidianBlack: '#0A0A0A',
  elevatedSurface: '#141414',
  darkSlate: '#1C1C1C',
  vibrantMint: '#00E676',
  forestGreen: '#0F3D2E',
  offWhite: '#F5F5F5',
  softGrey: '#A1A1A1',
  coolCharcoal: '#2A2A2A',
  coralRed: '#FF5C5C',
  freshGreen: '#22C55E',
  mutedGrey: '#525252',
  transparent: 'transparent',
  white: '#FFFFFF',
  black: '#000000',
  yellow: '#FACC15',
};

export const colors = {
  background: BASE_COLORS.obsidianBlack,
  card: BASE_COLORS.elevatedSurface,
  input: BASE_COLORS.darkSlate,
  primary: BASE_COLORS.vibrantMint,
  secondary: BASE_COLORS.forestGreen,
  text: BASE_COLORS.offWhite,
  textSecondary: BASE_COLORS.softGrey,
  border: BASE_COLORS.coolCharcoal,
  error: BASE_COLORS.coralRed,
  success: BASE_COLORS.freshGreen,
  disabled: BASE_COLORS.mutedGrey,
  warning: BASE_COLORS.coralRed,
  info: BASE_COLORS.offWhite,
  gradientStart: BASE_COLORS.vibrantMint,
  gradientEnd: BASE_COLORS.forestGreen,
  transparent: BASE_COLORS.transparent,
  gold: BASE_COLORS.yellow,
  // Convenience aliases
  accentPremium: BASE_COLORS.vibrantMint,
  surface: BASE_COLORS.elevatedSurface,
  surfaceInput: BASE_COLORS.darkSlate,
};
